Add Codecov integration

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -179,6 +179,7 @@ jobs:
           --verbose \
           --cov=plex_auto_languages \
           --cov-report term-missing \
+          --cov-append \
           tests
 
     - name: Unlink PMS from MyPlex account
@@ -186,3 +187,56 @@ jobs:
       run: |
         . venv/bin/activate
         python -u tools/plex_teardown.py
+
+    - name: Upload coverage artifact
+      uses: actions/upload-artifact@v3
+      with:
+        name: coverage-${{ matrix.plex }}-${{ matrix.python-version }}
+        path: .coverage
+
+  coverage:
+    name: upload coverage to codecov
+    runs-on: ubuntu-20.04
+    needs: pytest
+    if: always()
+    strategy:
+      matrix:
+        python-version: ["3.8"]
+        plex: ["claimed"]
+    steps:
+    - name: Check out code from GitHub
+      uses: actions/checkout@v3
+
+    - name: Set up Python ${{ matrix.python-version }}
+      id: python
+      uses: actions/setup-python@v3
+      with:
+        python-version: ${{ matrix.python-version }}
+
+    - name: Restore Python ${{ matrix.python-version }} virtual environment
+      id: cache-venv
+      uses: actions/cache@v3
+      with:
+        path: venv
+        key: ${{ env.CACHE_VERSION }}-${{ runner.os }}-venv-${{ steps.python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
+
+    - name: Fail job if Python cache restore failed
+      if: steps.cache-venv.outputs.cache-hit != 'true'
+      run: |
+        echo "Failed to restore Python virtual environment from cache"
+        exit 1
+
+    - name: Download all coverage artifacts
+      uses: actions/download-artifact@v3
+
+    - name: Combine ${{ matrix.plex }} coverage results
+      run: |
+        . venv/bin/activate
+        coverage combine coverage-${{ matrix.plex }}*/.coverage*
+        coverage report --fail-under=50
+        coverage xml
+
+    - name: Upload ${{ matrix.plex }} coverage to Codecov
+      uses: codecov/codecov-action@v2.1.0
+      with:
+        flags: ${{ matrix.plex }}
